### ISSUE TITLE
为什么不使用Rxbus呢？

### ISSUE THREAD

**Issue by MichaelJokAr** [uin3566/Dota2Helper#3]
看到了你的项目里用了rxjava并且使用了otto，那么为什么不用rxbus来代替otto呢

**Comment by uin3566** [comment]
嗯，这是我疏忽了，以前都用otto，这是我第一次用rxjava，刚开始还不知道有rxbus这玩意，就用了otto，我抽空把这个改了，省去一个依赖。多谢提醒~

**Comment by MichaelJokAr** [comment]
http://blog.csdn.net/a1018875550/article/details/52083187
嘿嘿，我写的关于rxbus，请多指教（：
