### ISSUE TITLE
请问Retrofit怎么在Token失效后刷新Token？

### ISSUE THREAD

**Issue by ghost** [uin3566/Dota2Helper#4]
我现在每个接口中都需要Token值作为参数，当Token失效后就要重新刷新token然后继续这次请求，请问怎么实现啊？有比较好的例子么..

**Comment by uin3566** [comment]
这貌似是业务层面的东西，收到token失效的通知以后使用retrofit调用更新token的接口更新token就行了，此时其他接口需要等有效token返回再继续请求。后台应该会告诉token的有效期吧，客户端起一个定时器刷新token就ok了。
