### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by Shvier** [uin3566/Dota2Helper#9]
hi xufang: 
[iOS版本](https://github.com/Shvier/Dota2Helper)目前做了几个界面，除了资讯这一项，其他都没有找到详细的API，不知道是否漏看，希望能告知。
附上邮箱[Shvier@sina.com](mailto:Shvier@sina.com)和截图:
![https://github.com/Shvier/PhotoLibrary/blob/master/Simulator%20Screen%20Shot%20Oct%205,%202016,%201.13.13%20AM.png?raw=true](https://github.com/Shvier/PhotoLibrary/blob/master/Simulator%20Screen%20Shot%20Oct%205,%202016,%201.13.13%20AM.png?raw=true)
![https://github.com/Shvier/PhotoLibrary/blob/master/Simulator%20Screen%20Shot%20Oct%205,%202016,%201.13.37%20AM.png?raw=true](https://github.com/Shvier/PhotoLibrary/blob/master/Simulator%20Screen%20Shot%20Oct%205,%202016,%201.13.37%20AM.png?raw=true)
![https://github.com/Shvier/PhotoLibrary/blob/master/Simulator%20Screen%20Shot%20Oct%205,%202016,%201.13.42%20AM.png?raw=true](https://github.com/Shvier/PhotoLibrary/blob/master/Simulator%20Screen%20Shot%20Oct%205,%202016,%201.13.42%20AM.png?raw=true)

**Comment by uin3566** [comment]
所有的接口都在Dota2Helper\app\src\main\java\com\fangxu\dota2helper\network文件夹下的文件里面定义了。。
